
name: vegan_power
description: Vegan Power Game

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flame: ^1.6.0
  shared_preferences: ^2.1.0
  flame_audio: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg/
    - assets/images/branding/
    - assets/images/icons/
    - assets/images/ui/
    - assets/images/units/
    - assets/audio/music/
    - assets/audio/sfx/
